[package]
name = "cw-pir-escrow"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
overflow-checks = true

[dependencies]
cosmwasm-std = "1.5"
cw-storage-plus = "1.2"
serde = { version = "1", features = ["derive"] }
schemars = "0.8"
hex = "0.4"
sha2 = "0.10"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-orch = "0.24"
hosting-payment = { path = "../circuits/hosting-payment" }
